// ============================================================================
// 📚 RAIO ECOSYSTEM - MOCK BOOKS DATA
// Livros de exemplo para a Biblioteca
// ============================================================================

import { Book } from './types/BookTypes';

export const mockBooks: Book[] = [
  {
    id: 'book-1',
    title: 'Os 5 Pilares de um Casamento Feliz',
    author: 'Dr. João Silva',
    coverImage: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc?w=400&h=600&fit=crop',
    description: 'Descubra os fundamentos essenciais para construir um relacionamento duradouro e feliz. Este livro apresenta estratégias práticas baseadas em décadas de pesquisa e experiência clínica.',
    category: ['Relacionamentos', 'Casamento', 'Autoajuda'],
    pages: 200,
    currentPage: 164,
    progress: 82,
    isCompleted: false,
    lastRead: new Date('2025-10-22'),
    estimatedReadTime: '1h 12min',
    rating: 5,
    isFavorite: true,
    isEnrolled: true,
    notes: [],
    highlights: [],
    format: 'pdf',
    fileUrl: '/books/5-pilares-casamento.pdf',
    isPremium: false,
    price: 0,
    readers: 1240,
    averageRating: 4.8,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2023,
    publisher: 'Editora RAIO',
    tags: ['casamento', 'relacionamento', 'família'],
    difficulty: 'beginner',
  },
  {
    id: 'book-2',
    title: 'Educação Positiva: Criando Filhos Resilientes',
    author: 'Dra. Maria Santos',
    coverImage: 'https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&h=600&fit=crop',
    description: 'Aprenda técnicas comprovadas de disciplina positiva para criar filhos emocionalmente inteligentes e resilientes. Com exemplos práticos e estudos de caso reais.',
    category: ['Parentalidade', 'Educação', 'Desenvolvimento Infantil'],
    pages: 280,
    currentPage: 126,
    progress: 45,
    isCompleted: false,
    lastRead: new Date('2025-10-20'),
    estimatedReadTime: '5h 8min',
    rating: 4,
    isFavorite: false,
    isEnrolled: true,
    notes: [],
    highlights: [],
    format: 'pdf',
    fileUrl: '/books/educacao-positiva.pdf',
    isPremium: true,
    price: 39.90,
    readers: 980,
    averageRating: 4.9,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2024,
    publisher: 'Editora RAIO',
    tags: ['filhos', 'educação', 'parentalidade'],
    difficulty: 'intermediate',
  },
  {
    id: 'book-3',
    title: 'Finanças do Casal: Prosperidade Juntos',
    author: 'Carlos Oliveira',
    coverImage: 'https://images.unsplash.com/photo-1554224311-beee460201e4?w=400&h=600&fit=crop',
    description: 'Organize suas finanças familiares e construa prosperidade juntos. Métodos práticos para orçamento, investimentos e planejamento financeiro a dois.',
    category: ['Finanças', 'Casamento', 'Economia Doméstica'],
    pages: 156,
    currentPage: 156,
    progress: 100,
    isCompleted: true,
    lastRead: new Date('2025-10-15'),
    estimatedReadTime: '0min',
    rating: 5,
    isFavorite: true,
    isEnrolled: true,
    notes: [],
    highlights: [],
    format: 'pdf',
    fileUrl: '/books/financas-casal.pdf',
    isPremium: false,
    price: 0,
    readers: 2100,
    averageRating: 4.6,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2023,
    publisher: 'Editora RAIO',
    tags: ['finanças', 'casal', 'investimentos'],
    difficulty: 'beginner',
  },
  {
    id: 'book-4',
    title: 'Comunicação Não-Violenta em Família',
    author: 'Ana Paula Costa',
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&h=600&fit=crop',
    description: 'Transforme a comunicação em sua família com técnicas de CNV. Aprenda a expressar necessidades, ouvir com empatia e resolver conflitos de forma construtiva.',
    category: ['Comunicação', 'Relacionamentos', 'Família'],
    pages: 188,
    currentPage: 45,
    progress: 24,
    isCompleted: false,
    lastRead: new Date('2025-10-18'),
    estimatedReadTime: '4h 46min',
    isFavorite: false,
    isEnrolled: true,
    notes: [],
    highlights: [],
    format: 'pdf',
    fileUrl: '/books/comunicacao-nao-violenta.pdf',
    isPremium: false,
    price: 0,
    readers: 1580,
    averageRating: 4.7,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2024,
    publisher: 'Editora RAIO',
    tags: ['comunicação', 'CNV', 'família'],
    difficulty: 'intermediate',
  },
  {
    id: 'book-5',
    title: 'A Arte de Educar sem Gritar',
    author: 'Pedro Henrique Lima',
    coverImage: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=600&fit=crop',
    description: 'Descubra estratégias eficazes para educar seus filhos sem gritos, ameaças ou punições. Baseado em neurociência e psicologia infantil.',
    category: ['Parentalidade', 'Educação', 'Comportamento'],
    pages: 224,
    currentPage: 0,
    progress: 0,
    isCompleted: false,
    isFavorite: false,
    isEnrolled: true,
    notes: [],
    highlights: [],
    format: 'pdf',
    fileUrl: '/books/educar-sem-gritar.pdf',
    isPremium: true,
    price: 29.90,
    readers: 756,
    averageRating: 4.8,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2024,
    publisher: 'Editora RAIO',
    tags: ['educação', 'disciplina', 'parentalidade'],
    difficulty: 'beginner',
  },
  {
    id: 'book-6',
    title: 'Intimidade e Conexão no Casamento',
    author: 'Juliana Rodrigues',
    coverImage: 'https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?w=400&h=600&fit=crop',
    description: 'Fortaleça a intimidade emocional e física em seu casamento. Um guia prático para casais que desejam aprofundar sua conexão.',
    category: ['Casamento', 'Intimidade', 'Relacionamentos'],
    pages: 176,
    currentPage: 88,
    progress: 50,
    isCompleted: false,
    lastRead: new Date('2025-10-21'),
    estimatedReadTime: '2h 56min',
    rating: 4,
    isFavorite: true,
    isEnrolled: true,
    notes: [],
    highlights: [],
    format: 'pdf',
    fileUrl: '/books/intimidade-casamento.pdf',
    isPremium: true,
    price: 34.90,
    readers: 892,
    averageRating: 4.9,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2023,
    publisher: 'Editora RAIO',
    tags: ['intimidade', 'casamento', 'conexão'],
    difficulty: 'intermediate',
  },
  {
    id: 'book-7',
    title: 'Propósito de Vida: Encontrando seu Chamado',
    author: 'Ricardo Almeida',
    coverImage: 'https://images.unsplash.com/photo-1513001900722-370f803f498d?w=400&h=600&fit=crop',
    description: 'Descubra seu propósito e viva uma vida com significado. Exercícios práticos e reflexões profundas para encontrar sua vocação.',
    category: ['Propósito', 'Desenvolvimento Pessoal', 'Espiritualidade'],
    pages: 240,
    currentPage: 0,
    progress: 0,
    isCompleted: false,
    isFavorite: false,
    isEnrolled: false,
    notes: [],
    highlights: [],
    format: 'pdf',
    isPremium: false,
    price: 0,
    readers: 1420,
    averageRating: 4.7,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2024,
    publisher: 'Editora RAIO',
    tags: ['propósito', 'vocação', 'significado'],
    difficulty: 'intermediate',
  },
  {
    id: 'book-8',
    title: 'Gestão do Tempo para Pais Ocupados',
    author: 'Fernanda Martins',
    coverImage: 'https://images.unsplash.com/photo-1495364141860-b0d03eccd065?w=400&h=600&fit=crop',
    description: 'Organize sua rotina e encontre equilíbrio entre trabalho, família e autocuidado. Técnicas práticas de gestão de tempo para pais modernos.',
    category: ['Produtividade', 'Parentalidade', 'Rotina'],
    pages: 192,
    currentPage: 0,
    progress: 0,
    isCompleted: false,
    isFavorite: false,
    isEnrolled: false,
    notes: [],
    highlights: [],
    format: 'pdf',
    isPremium: true,
    price: 27.90,
    readers: 634,
    averageRating: 4.5,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2024,
    publisher: 'Editora RAIO',
    tags: ['tempo', 'produtividade', 'pais'],
    difficulty: 'beginner',
  },
  {
    id: 'book-9',
    title: 'Saúde Mental da Família Moderna',
    author: 'Dr. Lucas Ferreira',
    coverImage: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&h=600&fit=crop',
    description: 'Cuide da saúde mental de toda a família. Estratégias para lidar com ansiedade, estresse e desafios emocionais do mundo moderno.',
    category: ['Saúde Mental', 'Família', 'Bem-estar'],
    pages: 264,
    currentPage: 0,
    progress: 0,
    isCompleted: false,
    isFavorite: false,
    isEnrolled: false,
    notes: [],
    highlights: [],
    format: 'pdf',
    isPremium: false,
    price: 0,
    readers: 1123,
    averageRating: 4.8,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2023,
    publisher: 'Editora RAIO',
    tags: ['saúde mental', 'ansiedade', 'família'],
    difficulty: 'intermediate',
  },
  {
    id: 'book-10',
    title: 'Criando Vínculos Seguros com seus Filhos',
    author: 'Beatriz Camargo',
    coverImage: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=400&h=600&fit=crop',
    description: 'Entenda a teoria do apego e como criar vínculos seguros que durarão a vida toda. Baseado em pesquisas científicas sobre desenvolvimento infantil.',
    category: ['Parentalidade', 'Apego', 'Desenvolvimento'],
    pages: 208,
    currentPage: 0,
    progress: 0,
    isCompleted: false,
    isFavorite: false,
    isEnrolled: false,
    notes: [],
    highlights: [],
    format: 'pdf',
    isPremium: true,
    price: 32.90,
    readers: 567,
    averageRating: 4.9,
    reviews: [],
    language: 'pt-BR',
    publishedYear: 2024,
    publisher: 'Editora RAIO',
    tags: ['apego', 'vínculos', 'desenvolvimento'],
    difficulty: 'advanced',
  },
];

// Helper: Filtrar livros por categoria
export function getBooksByCategory(category: string): Book[] {
  return mockBooks.filter(book => 
    book.category.some(c => c.toLowerCase().includes(category.toLowerCase()))
  );
}

// Helper: Livros em leitura (enrolled e não completados)
export function getReadingBooks(): Book[] {
  return mockBooks.filter(book => book.isEnrolled && !book.isCompleted);
}

// Helper: Livros completos
export function getCompletedBooks(): Book[] {
  return mockBooks.filter(book => book.isCompleted);
}

// Helper: Livros favoritos
export function getFavoriteBooks(): Book[] {
  return mockBooks.filter(book => book.isFavorite);
}

// Helper: Livros do marketplace (não enrolled)
export function getMarketplaceBooks(): Book[] {
  return mockBooks.filter(book => !book.isEnrolled);
}

// Helper: Livros enrolled (na biblioteca)
export function getEnrolledBooks(): Book[] {
  return mockBooks.filter(book => book.isEnrolled);
}
