// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lp-casados/Aspirational.tsx": () => import("../components/mockups/lp-casados/Aspirational.tsx"),
  "./components/mockups/lp-casados/Pragmatic.tsx": () => import("../components/mockups/lp-casados/Pragmatic.tsx")
};
